package vista;

import modelos.Articulo;
import servicios.ArticuloService;

/**
 *
 * @author Usuario
 */
public class VtnConsultarArticulo extends javax.swing.JInternalFrame {

    private ArticuloService objArticuloService;
    
    public VtnConsultarArticulo(ArticuloService objArticuloService) {
        initComponents();
        this.objArticuloService=objArticuloService;
        this.jLabelMensaje.setVisible(false);         
        this.jPanelMostrarDatos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelId = new javax.swing.JLabel();
        jTextFieldIdArticulo = new javax.swing.JTextField();
        jButtonConsultar = new javax.swing.JButton();
        jLabelMensaje = new javax.swing.JLabel();
        jPanelMostrarDatos = new javax.swing.JPanel();
        jLabelIdA = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelAutores = new javax.swing.JLabel();
        jLabelCantidadA = new javax.swing.JLabel();
        jLabelRevista = new javax.swing.JLabel();
        jLabelMId = new javax.swing.JLabel();
        jLabelMNombre = new javax.swing.JLabel();
        jLabelMAutores = new javax.swing.JLabel();
        jLabelMCantA = new javax.swing.JLabel();
        jLabelMRevista = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Consultar Articulo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jLabel1)
                .addContainerGap(268, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelId.setText("Id:");

        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jLabelMensaje.setText("Mensaje");

        jPanelMostrarDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelIdA.setText("Id Articulo:");

        jLabelNombre.setText("Nombre:");

        jLabelAutores.setText("Autores:");

        jLabelCantidadA.setText("Cantidad Autores:");

        jLabelRevista.setText("Revista:");

        jLabelMId.setText("Resultado");

        jLabelMNombre.setText("Resultado");

        jLabelMAutores.setText("Resultado");

        jLabelMCantA.setText("Resultado");

        jLabelMRevista.setText("Resultado");

        javax.swing.GroupLayout jPanelMostrarDatosLayout = new javax.swing.GroupLayout(jPanelMostrarDatos);
        jPanelMostrarDatos.setLayout(jPanelMostrarDatosLayout);
        jPanelMostrarDatosLayout.setHorizontalGroup(
            jPanelMostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMostrarDatosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelMostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMostrarDatosLayout.createSequentialGroup()
                        .addComponent(jLabelCantidadA)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelMostrarDatosLayout.createSequentialGroup()
                        .addGroup(jPanelMostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabelIdA)
                            .addComponent(jLabelAutores)
                            .addComponent(jLabelRevista))
                        .addGap(160, 160, 160)
                        .addGroup(jPanelMostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMRevista)
                            .addComponent(jLabelMAutores)
                            .addComponent(jLabelMId)
                            .addComponent(jLabelMNombre)
                            .addComponent(jLabelMCantA))
                        .addContainerGap(228, Short.MAX_VALUE))))
        );
        jPanelMostrarDatosLayout.setVerticalGroup(
            jPanelMostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMostrarDatosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelMostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdA)
                    .addComponent(jLabelMId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelMNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAutores)
                    .addComponent(jLabelMAutores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCantidadA)
                    .addComponent(jLabelMCantA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRevista)
                    .addComponent(jLabelMRevista))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMensaje)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelId)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldIdArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jButtonConsultar))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanelMostrarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId)
                    .addComponent(jTextFieldIdArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelMostrarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
       String idArticulo;
       Integer idArticuloEntero;
       idArticulo=this.jTextFieldIdArticulo.getText();
       idArticuloEntero=Integer.parseInt(idArticulo);
       
       if(this.objArticuloService.consultarSiExisteArticulo(idArticuloEntero))
       {
            this.jLabelMensaje.setVisible(false);
            this.jPanelMostrarDatos.setVisible(true);
            Articulo objArticulo=this.objArticuloService.consultarArticulo(idArticuloEntero);
            this.jLabelMId.setText(objArticulo.getId()+"");
            this.jLabelMNombre.setText(objArticulo.getNombre());
            this.jLabelMAutores.setText(objArticulo.getAutores());
            this.jLabelMCantA.setText(String.valueOf(objArticulo.getCantidadAutores()));
            this.jLabelMRevista.setText(objArticulo.getRevista());
       }
       else
       {
           this.jLabelMensaje.setVisible(true);
           this.jLabelMensaje.setText("Error, no existe un articulo con ese identificador");
           this.jPanelMostrarDatos.setVisible(false);
       }
    }//GEN-LAST:event_jButtonConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAutores;
    private javax.swing.JLabel jLabelCantidadA;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelIdA;
    private javax.swing.JLabel jLabelMAutores;
    private javax.swing.JLabel jLabelMCantA;
    private javax.swing.JLabel jLabelMId;
    private javax.swing.JLabel jLabelMNombre;
    private javax.swing.JLabel jLabelMRevista;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelRevista;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelMostrarDatos;
    private javax.swing.JTextField jTextFieldIdArticulo;
    // End of variables declaration//GEN-END:variables
}
