package vista;

import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import modelos.Articulo;
import servicios.ArticuloService;
import utilidades.Utilidades;
/**
 *
 * @author Usuario
 */
public class VtnGestionarArticulos extends javax.swing.JInternalFrame {

    private final ArticuloService objArticuloService;
    
    public VtnGestionarArticulos(ArticuloService objArticuloService) {
        initComponents();
        this.objArticuloService=objArticuloService;
        this.jTableMostrarArticulos.setDefaultRenderer(Object.class, new Render());
        inicializarTabla();
    }

     private void inicializarTabla()
    {
       DefaultTableModel model= new DefaultTableModel();       
       model.addColumn("Id");
       model.addColumn("Nombre");
       model.addColumn("Autores");
       model.addColumn("Cantidad de Autores");
       model.addColumn("Revista");
       model.addColumn("actualizar");
       model.addColumn("eliminar");
       this.jTableMostrarArticulos.setModel(model);
    }
    
     public void limpiarTabla(){
        
        DefaultTableModel modelo=(DefaultTableModel) this.jTableMostrarArticulos.getModel();
        int filas=this.jTableMostrarArticulos.getRowCount();
        for (int i = 0;filas>i; i++) {
            modelo.removeRow(0);
        }        
    }
     
     private void llenarTabla()
    {
        DefaultTableModel model=(DefaultTableModel) this.jTableMostrarArticulos.getModel();
        limpiarTabla();
        List<Articulo> lista= this.objArticuloService.listarArticulos();
        
        for (int i = 0; i < lista.size(); i++) {
            
            JButton JButtonActualizarArticulo = new JButton();
            JButtonActualizarArticulo.setName("Actualizar");
            JButtonActualizarArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/lapiz.png")));

            
            JButton JButtonEliminarArticulo = new JButton();
            JButtonEliminarArticulo.setName("Eliminar");
            JButtonEliminarArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/remove.png")));

            
            Object [] fila= { lista.get(i).getId()+"", lista.get(i).getNombre(), lista.get(i).getAutores(), lista.get(i).getCantidadAutores(),lista.get(i).getRevista(),JButtonActualizarArticulo,JButtonEliminarArticulo};
            model.addRow(fila);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonActualizar = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMostrarArticulos = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelTitulo.setText("Gestionar Articulos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(398, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(392, 392, 392))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabelTitulo)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jTableMostrarArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableMostrarArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMostrarArticulosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMostrarArticulos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jButtonActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 463, Short.MAX_VALUE)
                .addComponent(jButtonRegistrar)
                .addGap(152, 152, 152))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonActualizar)
                    .addComponent(jButtonRegistrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        llenarTabla();  
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
       VtnRegistrarArticulo VtnObjRegistrarArticulo = new VtnRegistrarArticulo(this.objArticuloService);
       VtnObjRegistrarArticulo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       VtnObjRegistrarArticulo.setVisible(true);
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jTableMostrarArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMostrarArticulosMouseClicked
        int column = this.jTableMostrarArticulos.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/jTableMostrarArticulos.getRowHeight();
        
        if(row < jTableMostrarArticulos.getRowCount() && row >= 0 && column < jTableMostrarArticulos.getColumnCount() && column >= 0){
            Object value = jTableMostrarArticulos.getValueAt(row, column);
            
            if(value instanceof JButton){
                
                ((JButton)value).doClick();
                JButton boton = (JButton) value;
                
                String idArticulo = jTableMostrarArticulos.getValueAt(row, 0).toString();
               
                if(boton.getName().equals("Eliminar")){
                   this.elimininarArticulo(idArticulo);
                }
                else if(boton.getName().equals("Actualizar")){
                   this.actualizarArticulo(idArticulo);
                }
            }
        }
    }//GEN-LAST:event_jTableMostrarArticulosMouseClicked
 private void actualizarArticulo(String idArticulo)
    {
        Integer idArticuloEntero=Integer.parseInt(idArticulo);
        Articulo objArticulo= this.objArticuloService.consultarArticulo(idArticuloEntero);
        VtnActualizarArticulo VtnObjActualizarArticulo= new VtnActualizarArticulo(this.objArticuloService);
        VtnObjActualizarArticulo.actualizarFormularioArticulo(idArticuloEntero, objArticulo);
        VtnObjActualizarArticulo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        VtnObjActualizarArticulo.setVisible(true);
    }   
    private void elimininarArticulo(String idArticulo)
    {
        try{  
                if(Utilidades.mensajeConfirmacion(" Estas seguro de que quieres eliminar al cliente con id " + idArticulo + " " 
                    +" ?", "Confirmacion") == 0){
                   Integer idArticuloEntero=Integer.parseInt(idArticulo); 
                   boolean bandera=this.objArticuloService.eliminarArticulo(idArticuloEntero);
                   if(bandera==true)
                   {
                       Utilidades.mensajeExito("El cliente con id " + idArticulo + " fue eliminado exitosamente", "Cliente eliminado");
                       llenarTabla();
                   }
                   else
                   {
                       Utilidades.mensajeAdvertencia("El cliente con id " + idArticulo + " no fue eliminado", "Error al eliminar");

                   }
                }
            }catch(Exception ex){
                Utilidades.mensajeError("Error al eliminar el cliente. Intentelo de nuevo mas tarde", "Error");
        }  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMostrarArticulos;
    // End of variables declaration//GEN-END:variables
}
